export const DEFAULT_LANGUAGE = "eng_Latn";

export const SUPPORTED_LANGUAGES = [
  { "Language": "Acehnese (Arabic script)", "ISO": "ace_Arab" },
  { "Language": "Acehnese (Latin script)", "ISO": "ace_Latn" },
  { "Language": "Mesopotamian Arabic", "ISO": "acm_Arab" },
  { "Language": "Ta’izzi-Adeni Arabic", "ISO": "acq_Arab" },
  { "Language": "Tunisian Arabic", "ISO": "aeb_Arab" },
  { "Language": "Afrikaans", "ISO": "afr_Latn" },
  { "Language": "South Levantine Arabic", "ISO": "ajp_Arab" },
  { "Language": "Akan", "ISO": "aka_Latn" },
  { "Language": "Amharic", "ISO": "amh_Ethi" },
  { "Language": "North Levantine Arabic", "ISO": "apc_Arab" },
  { "Language": "Modern Standard Arabic", "ISO": "arb_Arab" },
  { "Language": "Modern Standard Arabic (Romanized)", "ISO": "arb_Latn" },
  { "Language": "Najdi Arabic", "ISO": "ars_Arab" },
  { "Language": "Moroccan Arabic", "ISO": "ary_Arab" },
  { "Language": "Egyptian Arabic", "ISO": "arz_Arab" },
  { "Language": "Assamese", "ISO": "asm_Beng" },
  { "Language": "Asturian", "ISO": "ast_Latn" },
  { "Language": "Awadhi", "ISO": "awa_Deva" },
  { "Language": "Central Aymara", "ISO": "ayr_Latn" },
  { "Language": "South Azerbaijani", "ISO": "azb_Arab" },
  { "Language": "North Azerbaijani", "ISO": "azj_Latn" },
  { "Language": "Bashkir", "ISO": "bak_Cyrl" },
  { "Language": "Bambara", "ISO": "bam_Latn" },
  { "Language": "Balinese", "ISO": "ban_Latn" },
  { "Language": "Belarusian", "ISO": "bel_Cyrl" },
  { "Language": "Bemba", "ISO": "bem_Latn" },
  { "Language": "Bengali", "ISO": "ben_Beng" },
  { "Language": "Bhojpuri", "ISO": "bho_Deva" },
  { "Language": "Banjar (Arabic script)", "ISO": "bjn_Arab" },
  { "Language": "Banjar (Latin script)", "ISO": "bjn_Latn" },
  { "Language": "Standard Tibetan", "ISO": "bod_Tibt" },
  { "Language": "Bosnian", "ISO": "bos_Latn" },
  { "Language": "Buginese", "ISO": "bug_Latn" },
  { "Language": "Bulgarian", "ISO": "bul_Cyrl" },
  { "Language": "Catalan", "ISO": "cat_Latn" },
  { "Language": "Cebuano", "ISO": "ceb_Latn" },
  { "Language": "Czech", "ISO": "ces_Latn" },
  { "Language": "Chokwe", "ISO": "cjk_Latn" },
  { "Language": "Central Kurdish", "ISO": "ckb_Arab" },
  { "Language": "Crimean Tatar", "ISO": "crh_Latn" },
  { "Language": "Welsh", "ISO": "cym_Latn" },
  { "Language": "Danish", "ISO": "dan_Latn" },
  { "Language": "German", "ISO": "deu_Latn" },
  { "Language": "Southwestern Dinka", "ISO": "dik_Latn" },
  { "Language": "Dyula", "ISO": "dyu_Latn" },
  { "Language": "Dzongkha", "ISO": "dzo_Tibt" },
  { "Language": "Greek", "ISO": "ell_Grek" },
  { "Language": "English", "ISO": "eng_Latn" },
  { "Language": "Esperanto", "ISO": "epo_Latn" },
  { "Language": "Estonian", "ISO": "est_Latn" },
  { "Language": "Basque", "ISO": "eus_Latn" },
  { "Language": "Ewe", "ISO": "ewe_Latn" },
  { "Language": "Faroese", "ISO": "fao_Latn" },
  { "Language": "Fijian", "ISO": "fij_Latn" },
  { "Language": "Finnish", "ISO": "fin_Latn" },
  { "Language": "Fon", "ISO": "fon_Latn" },
  { "Language": "French", "ISO": "fra_Latn" },
  { "Language": "Friulian", "ISO": "fur_Latn" },
  { "Language": "Nigerian Fulfulde", "ISO": "fuv_Latn" },
  { "Language": "Scottish Gaelic", "ISO": "gla_Latn" },
  { "Language": "Irish", "ISO": "gle_Latn" },
  { "Language": "Galician", "ISO": "glg_Latn" },
  { "Language": "Guarani", "ISO": "grn_Latn" },
  { "Language": "Gujarati", "ISO": "guj_Gujr" },
  { "Language": "Haitian Creole", "ISO": "hat_Latn" },
  { "Language": "Hausa", "ISO": "hau_Latn" },
  { "Language": "Hebrew", "ISO": "heb_Hebr" },
  { "Language": "Hindi", "ISO": "hin_Deva" },
  { "Language": "Chhattisgarhi", "ISO": "hne_Deva" },
  { "Language": "Croatian", "ISO": "hrv_Latn" },
  { "Language": "Hungarian", "ISO": "hun_Latn" },
  { "Language": "Armenian", "ISO": "hye_Armn" },
  { "Language": "Igbo", "ISO": "ibo_Latn" },
  { "Language": "Ilocano", "ISO": "ilo_Latn" },
  { "Language": "Indonesian", "ISO": "ind_Latn" },
  { "Language": "Icelandic", "ISO": "isl_Latn" },
  { "Language": "Italian", "ISO": "ita_Latn" },
  { "Language": "Javanese", "ISO": "jav_Latn" },
  { "Language": "Japanese", "ISO": "jpn_Jpan" },
  { "Language": "Kabyle", "ISO": "kab_Latn" },
  { "Language": "Jingpho", "ISO": "kac_Latn" },
  { "Language": "Kamba", "ISO": "kam_Latn" },
  { "Language": "Kannada", "ISO": "kan_Knda" },
  { "Language": "Kashmiri (Arabic script)", "ISO": "kas_Arab" },
  { "Language": "Kashmiri (Devanagari script)", "ISO": "kas_Deva" },
  { "Language": "Georgian", "ISO": "kat_Geor" },
  { "Language": "Central Kanuri (Arabic script)", "ISO": "knc_Arab" },
  { "Language": "Central Kanuri (Latin script)", "ISO": "knc_Latn" },
  { "Language": "Kazakh", "ISO": "kaz_Cyrl" },
  { "Language": "Kabiyè", "ISO": "kbp_Latn" },
  { "Language": "Kabuverdianu", "ISO": "kea_Latn" },
  { "Language": "Khmer", "ISO": "khm_Khmr" },
  { "Language": "Kikuyu", "ISO": "kik_Latn" },
  { "Language": "Kinyarwanda", "ISO": "kin_Latn" },
  { "Language": "Kyrgyz", "ISO": "kir_Cyrl" },
  { "Language": "Kimbundu", "ISO": "kmb_Latn" },
  { "Language": "Northern Kurdish", "ISO": "kmr_Latn" },
  { "Language": "Kikongo", "ISO": "kon_Latn" },
  { "Language": "Korean", "ISO": "kor_Hang" },
  { "Language": "Lao", "ISO": "lao_Laoo" },
  { "Language": "Ligurian", "ISO": "lij_Latn" },
  { "Language": "Limburgish", "ISO": "lim_Latn" },
  { "Language": "Lingala", "ISO": "lin_Latn" },
  { "Language": "Lithuanian", "ISO": "lit_Latn" },
  { "Language": "Lombard", "ISO": "lmo_Latn" },
  { "Language": "Latgalian", "ISO": "ltg_Latn" },
  { "Language": "Luxembourgish", "ISO": "ltz_Latn" },
  { "Language": "Luba-Kasai", "ISO": "lua_Latn" },
  { "Language": "Ganda", "ISO": "lug_Latn" },
  { "Language": "Luo", "ISO": "luo_Latn" },
  { "Language": "Mizo", "ISO": "lus_Latn" },
  { "Language": "Standard Latvian", "ISO": "lvs_Latn" },
  { "Language": "Magahi", "ISO": "mag_Deva" },
  { "Language": "Maithili", "ISO": "mai_Deva" },
  { "Language": "Malayalam", "ISO": "mal_Mlym" },
  { "Language": "Marathi", "ISO": "mar_Deva" },
  { "Language": "Minangkabau (Arabic script)", "ISO": "min_Arab" },
  { "Language": "Minangkabau (Latin script)", "ISO": "min_Latn" },
  { "Language": "Macedonian", "ISO": "mkd_Cyrl" },
  { "Language": "Plateau Malagasy", "ISO": "plt_Latn" },
  { "Language": "Maltese", "ISO": "mlt_Latn" },
  { "Language": "Meitei (Bengali script)", "ISO": "mni_Beng" },
  { "Language": "Halh Mongolian", "ISO": "khk_Cyrl" },
  { "Language": "Mossi", "ISO": "mos_Latn" },
  { "Language": "Maori", "ISO": "mri_Latn" },
  { "Language": "Burmese", "ISO": "mya_Mymr" },
  { "Language": "Dutch", "ISO": "nld_Latn" },
  { "Language": "Norwegian Nynorsk", "ISO": "nno_Latn" },
  { "Language": "Norwegian Bokmål", "ISO": "nob_Latn" },
  { "Language": "Nepali", "ISO": "npi_Deva" },
  { "Language": "Northern Sotho", "ISO": "nso_Latn" },
  { "Language": "Nuer", "ISO": "nus_Latn" },
  { "Language": "Nyanja", "ISO": "nya_Latn" },
  { "Language": "Occitan", "ISO": "oci_Latn" },
  { "Language": "West Central Oromo", "ISO": "gaz_Latn" },
  { "Language": "Odia", "ISO": "ory_Orya" },
  { "Language": "Pangasinan", "ISO": "pag_Latn" },
  { "Language": "Eastern Panjabi", "ISO": "pan_Guru" },
  { "Language": "Papiamento", "ISO": "pap_Latn" },
  { "Language": "Western Persian", "ISO": "pes_Arab" },
  { "Language": "Polish", "ISO": "pol_Latn" },
  { "Language": "Portuguese", "ISO": "por_Latn" },
  { "Language": "Dari", "ISO": "prs_Arab" },
  { "Language": "Southern Pashto", "ISO": "pbt_Arab" },
  { "Language": "Ayacucho Quechua", "ISO": "quy_Latn" },
  { "Language": "Romanian", "ISO": "ron_Latn" },
  { "Language": "Rundi", "ISO": "run_Latn" },
  { "Language": "Russian", "ISO": "rus_Cyrl" },
  { "Language": "Sango", "ISO": "sag_Latn" },
  { "Language": "Sanskrit", "ISO": "san_Deva" },
  { "Language": "Santali", "ISO": "sat_Olck" },
  { "Language": "Sicilian", "ISO": "scn_Latn" },
  { "Language": "Shan", "ISO": "shn_Mymr" },
  { "Language": "Sinhala", "ISO": "sin_Sinh" },
  { "Language": "Slovak", "ISO": "slk_Latn" },
  { "Language": "Slovenian", "ISO": "slv_Latn" },
  { "Language": "Samoan", "ISO": "smo_Latn" },
  { "Language": "Shona", "ISO": "sna_Latn" },
  { "Language": "Sindhi", "ISO": "snd_Arab" },
  { "Language": "Somali", "ISO": "som_Latn" },
  { "Language": "Southern Sotho", "ISO": "sot_Latn" },
  { "Language": "Spanish", "ISO": "spa_Latn" },
  { "Language": "Tosk Albanian", "ISO": "als_Latn" },
  { "Language": "Sardinian", "ISO": "srd_Latn" },
  { "Language": "Serbian", "ISO": "srp_Cyrl" },
  { "Language": "Swati", "ISO": "ssw_Latn" },
  { "Language": "Sundanese", "ISO": "sun_Latn" },
  { "Language": "Swedish", "ISO": "swe_Latn" },
  { "Language": "Swahili", "ISO": "swh_Latn" },
  { "Language": "Silesian", "ISO": "szl_Latn" },
  { "Language": "Tamil", "ISO": "tam_Taml" },
  { "Language": "Tatar", "ISO": "tat_Cyrl" },
  { "Language": "Telugu", "ISO": "tel_Telu" },
  { "Language": "Tajik", "ISO": "tgk_Cyrl" },
  { "Language": "Tagalog", "ISO": "tgl_Latn" },
  { "Language": "Thai", "ISO": "tha_Thai" },
  { "Language": "Tigrinya", "ISO": "tir_Ethi" },
  { "Language": "Tamasheq (Latin script)", "ISO": "taq_Latn" },
  { "Language": "Tamasheq (Tifinagh script)", "ISO": "taq_Tfng" },
  { "Language": "Tok Pisin", "ISO": "tpi_Latn" },
  { "Language": "Tswana", "ISO": "tsn_Latn" },
  { "Language": "Tsonga", "ISO": "tso_Latn" },
  { "Language": "Turkmen", "ISO": "tuk_Latn" },
  { "Language": "Tumbuka", "ISO": "tum_Latn" },
  { "Language": "Turkish", "ISO": "tur_Latn" },
  { "Language": "Twi", "ISO": "twi_Latn" },
  { "Language": "Central Atlas Tamazight", "ISO": "tzm_Tfng" },
  { "Language": "Uyghur", "ISO": "uig_Arab" },
  { "Language": "Ukrainian", "ISO": "ukr_Cyrl" },
  { "Language": "Umbundu", "ISO": "umb_Latn" },
  { "Language": "Urdu", "ISO": "urd_Arab" },
  { "Language": "Northern Uzbek", "ISO": "uzn_Latn" },
  { "Language": "Venetian", "ISO": "vec_Latn" },
  { "Language": "Vietnamese", "ISO": "vie_Latn" },
  { "Language": "Waray", "ISO": "war_Latn" },
  { "Language": "Wolof", "ISO": "wol_Latn" },
  { "Language": "Xhosa", "ISO": "xho_Latn" },
  { "Language": "Eastern Yiddish", "ISO": "ydd_Hebr" },
  { "Language": "Yoruba", "ISO": "yor_Latn" },
  { "Language": "Yue Chinese", "ISO": "yue_Hant" },
  { "Language": "Chinese (Simplified)", "ISO": "zho_Hans" },
  { "Language": "Chinese (Traditional)", "ISO": "zho_Hant" },
  { "Language": "Standard Malay", "ISO": "zsm_Latn" },
  { "Language": "Zulu", "ISO": "zul_Latn" }
].sort((a, b) => a.Language.localeCompare(b.Language));;
