branch-defaults:
  default:
    environment: lingopal-classroom-dev
  main:
    environment: lingopal-classroom-prod
    group_suffix: null
  staging:
    environment: lingopal-classroom-dev
    group_suffix: null
environment-defaults:
  lingopal-classroom-dev:
    branch: null
    repository: null
global:
  application_name: lingopal-classroom
  branch: null
  default_ec2_keyname: avesh-classroom-key
  default_platform: Node.js 18 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
